/**
 * Fractional indexing for block order (DECISIONS.md D-004).
 *
 * A block's position is a string key. To insert between two blocks you generate a key that sorts
 * strictly between their keys — no other block is touched, so an insert is O(1) and produces exactly
 * one operation instead of renumbering the document.
 *
 * The alternative, integer positions, requires rewriting every subsequent block's index on each
 * insert: an N-operation write amplification for a single keystroke, and — far worse — N operations
 * that can conflict with a concurrent edit. Fractional indexing turns "insert a paragraph" from a
 * document-wide write into a local one.
 */

const DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
const BASE = DIGITS.length; // 62

const MIN_DIGIT = DIGITS[0]!; // "0"
const MAX_DIGIT = DIGITS[BASE - 1]!; // "z"

function digitValue(char: string): number {
  const index = DIGITS.indexOf(char);
  /* c8 ignore next -- keys are generated by this module and validated at the server boundary */
  if (index === -1) throw new Error(`invalid fractional index digit: ${char}`);
  return index;
}

/**
 * A key strictly between `before` and `after`. `null` means "unbounded on that side".
 *
 * The algorithm walks the two keys digit by digit while they agree, then finds room in the first
 * position where they differ. If there is no room (they are adjacent digits), it descends: it copies
 * `before`'s digit and recurses into the next position, which always terminates because appending a
 * digit to `before` always produces something greater than `before` and less than `after`.
 *
 * Keys therefore grow by one character in the pathological case of repeatedly inserting at the same
 * spot. That is real and bounded in practice (a user inserting 30 blocks between the same two blocks
 * produces a ~30-character key, which is fine); the server caps key length at 128 so a malicious
 * client cannot grow them without limit.
 */
export function generateKeyBetween(before: string | null, after: string | null): string {
  if (before !== null && after !== null && before >= after) {
    throw new Error(`fractional index out of order: ${before} >= ${after}`);
  }

  if (before === null && after === null) {
    // The first block in an empty document. Deliberately the middle of the space, not "0": starting
    // at the bottom means every subsequent "insert above" has to descend, growing keys immediately.
    return "V"; // ~midpoint of the 62-digit alphabet
  }

  if (before === null) {
    return keyBefore(after!);
  }

  if (after === null) {
    return keyAfter(before);
  }

  return keyBetween(before, after);
}

/** A key strictly less than `after`. */
function keyBefore(after: string): string {
  const firstDigit = digitValue(after[0]!);

  if (firstDigit > 0) {
    // There is room below the first digit: take the midpoint of [0, firstDigit).
    return DIGITS[Math.floor(firstDigit / 2)]!;
  }

  // `after` starts at the bottom of the alphabet ("0..."), so nothing shorter fits below it. Descend:
  // "0" + (a key before the rest). "0X" < "0..." for any X below the rest's first digit.
  return MIN_DIGIT + keyBefore(after.slice(1) === "" ? MAX_DIGIT : after.slice(1));
}

/** A key strictly greater than `before`. */
function keyAfter(before: string): string {
  const firstDigit = digitValue(before[0]!);

  if (firstDigit < BASE - 1) {
    return DIGITS[firstDigit + Math.max(1, Math.floor((BASE - 1 - firstDigit) / 2))]!;
  }

  // `before` starts at the top ("z..."): nothing of the same length fits above. Descend by keeping the
  // "z" and going after the remainder — "z" + anything > "z".
  return MAX_DIGIT + keyAfter(before.slice(1) === "" ? MIN_DIGIT : before.slice(1));
}

function keyBetween(before: string, after: string): string {
  let prefix = "";
  let index = 0;

  // Walk the common prefix. Two keys that agree for k digits differ only after them, so the answer
  // shares that prefix.
  while (true) {
    const beforeDigit = index < before.length ? digitValue(before[index]!) : -1;
    const afterDigit = index < after.length ? digitValue(after[index]!) : BASE;

    if (beforeDigit === afterDigit) {
      prefix += before[index]!;
      index += 1;
      continue;
    }

    const midpoint = Math.floor((beforeDigit + afterDigit) / 2);

    if (midpoint > beforeDigit) {
      // There is a digit strictly between them at this position. Done.
      return prefix + DIGITS[midpoint]!;
    }

    // The digits are adjacent (e.g. "b" and "c"): no room at this position. Keep `before`'s digit and
    // find a key strictly after the remainder of `before` — which is guaranteed to still be less than
    // `after`, because it shares `before`'s smaller digit at this position.
    const beforeRest = before.slice(index + 1);
    return prefix + (beforeDigit === -1 ? MIN_DIGIT : before[index]!) + keyAfter(beforeRest === "" ? MIN_DIGIT : beforeRest);
  }
}

/** N evenly-spaced keys after `before` — used when pasting or importing several blocks at once. */
export function generateKeysAfter(before: string | null, count: number, after: string | null = null): string[] {
  const keys: string[] = [];
  let cursor = before;

  for (let i = 0; i < count; i += 1) {
    const key = generateKeyBetween(cursor, after);
    keys.push(key);
    cursor = key;
  }

  return keys;
}
